# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='iphone',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
    ]
