# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161223_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收藏表',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻表'},
        ),
        migrations.AlterModelOptions(
            name='sendmsg',
            options={'verbose_name': '随机验证码表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.News', verbose_name='评论新闻ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='news',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='favor_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='nt',
            field=models.IntegerField(choices=[(1, '42区'), (2, '段子'), (3, '图片'), (4, '挨踢1024'), (5, '你问我答')], verbose_name='新闻类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=128, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=64, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(null=True, verbose_name='新闻URL'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=32, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='collection',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.News', verbose_name='收藏新闻ID'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo', verbose_name='用户'),
        ),
    ]
